select * from PRACTICE_DATABASE.PUBLIC.US_HOUSEHOLD_INCOME;

select * from PRACTICE_DATABASE.PUBLIC.US_HOUSEHOLD_INCOME_CLEANED;

select DISTINCT TIMESTAMP from PRACTICE_DATABASE.PUBLIC.US_HOUSEHOLD_INCOME_CLEANED;


DELIMITER &&
DROP PROCEDURE IF EXISTS PRACTICE_DATABASE.PUBLIC.Copy_and_Clean_Data();

CREATE PROCEDURE Copy_and_Clean_Data()
BEGIN
--- creating our table 
    create or replace TABLE PRACTICE_DATABASE.PUBLIC.US_HOUSEHOLD_INCOME_CLEANED (
    	ROW_ID NUMBER(38,0),
    	ID NUMBER(38,0),
    	STATE_CODE NUMBER(38,0),
    	STATE_NAME VARCHAR(16777216),
    	STATE_AB VARCHAR(16777216),
    	COUNTY VARCHAR(16777216),
    	CITY VARCHAR(16777216),
    	PLACE VARCHAR(16777216),
    	TYPE VARCHAR(16777216),
    	PRIMARY VARCHAR(16777216),
    	ZIP_CODE NUMBER(38,0),
    	AREA_CODE NUMBER(38,0),
    	ALAND NUMBER(38,0),
    	AWATER NUMBER(38,0),
    	LAT NUMBER(38,7),
    	LON NUMBER(38,7),
        TimeStamp TIMESTAMP Default NULL
        
    );

--- copy data to new table 
   INSERT INTO PRACTICE_DATABASE.PUBLIC.US_HOUSEHOLD_INCOME_CLEANED
   select * , CURRENT_TIMESTAMP
   from PRACTICE_DATABASE.PUBLIC.US_HOUSEHOLD_INCOME;

------------- Data Cleaning
    DELETE FROM PRACTICE_DATABASE.PUBLIC.US_HOUSEHOLD_INCOME 
    WHERE 
    	row_id IN (
    	SELECT row_id
    FROM (
    	SELECT row_id, id,
    		ROW_NUMBER() OVER (
    			PARTITION BY id
    			ORDER BY id) AS row_num
    	FROM 
    		PRACTICE_DATABASE.PUBLIC.US_HOUSEHOLD_INCOME
    ) duplicates
    WHERE 
    	row_num > 1
    );
    
    UPDATE PRACTICE_DATABASE.PUBLIC.US_HOUSEHOLD_INCOME_CLEANED
    SET State_Name = 'Georgia'
    WHERE State_Name = 'georia';
    
    UPDATE PRACTICE_DATABASE.PUBLIC.US_HOUSEHOLD_INCOME_CLEANED
    SET County = UPPER(County);
    
    UPDATE PRACTICE_DATABASE.PUBLIC.US_HOUSEHOLD_INCOME_CLEANED
    SET City = UPPER(City);
    
    UPDATE PRACTICE_DATABASE.PUBLIC.US_HOUSEHOLD_INCOME_CLEANED
    SET Place = UPPER(Place);
    
    UPDATE PRACTICE_DATABASE.PUBLIC.US_HOUSEHOLD_INCOME_CLEANED
    SET State_Name = UPPER(State_Name);
    
    UPDATE PRACTICE_DATABASE.PUBLIC.US_HOUSEHOLD_INCOME_CLEANED
    SET Type = 'CDP'
    WHERE Type = 'CPD';
    
    UPDATE PRACTICE_DATABASE.PUBLIC.US_HOUSEHOLD_INCOME_CLEANED
    SET Type = 'Borough'
    WHERE Type = 'Boroughs';
   

END &&
DELIMITER ;


CALL PRACTICE_DATABASE.PUBLIC.Copy_and_Clean_Data();


--create event 
CREATE EVENT run_data_cleaning
  ON SCHEDULE EVERY 2 MINUTE
  DO CALL PRACTICE_DATABASE.PUBLIC.Copy_and_Clean_Data();

--- create trigger 
DELIITER && 
CREATE TRIGGER transfer_clean_data
    AFTER INSERT ON PRACTICE_DATABASE.PUBLIC.US_HOUSEHOLD_INCOME
    FOR EACH ROW
BEGIN 
    CALL PRACTICE_DATABASE.PUBLIC.Copy_and_Clean_Data();
END  &&

DELIMITER ;

  

